### ISSUE TITLE
Speed up libcxx tests

### ISSUE THREAD

**Issue by andschwa** [openenclave/openenclave#1015]
Similar to #782, we should be able to massively speed up the build and run times of the full libcxx tests. Right now, these tests are disabled by default and only run at night because the build (on CI machines)  takes ~2hrs. @mikbras's idea goes like this:

- Group them together
- Includes all the C++ headers used by the tests first
- Define a namespace for this test (main) to be compiled in.
- By including the C++ headers first, putting the entire main source does not cause problems.
- The problem is that the tests define many clashing globals.
- So grouping them in namespaces seems to work.
-  We will have to work around the problem of putting the #includes's in the namespace too.

For libc tests, we worked around this by including the headers first and then including the main:

```
#include <vector>
namespace vector_test
{
    #include ".../vector_test.cpp"
}
```

Where `vector_test.cpp` includes `<vector>`. (The inclusion guards prevents inclusion of the headers within the namespace).

**Comment by anitagov** [comment]
Optimizing the libcxx tests to all run as one large test is not a great idea. These are the following issues that I encountered when enabling libc tests to run on Windows where all the 240 tests are run one after the other.
1) If one test fails, the libc test fails and the other libc tests are not even tried. So, running each test separately is better.
2) Right now, cross compilation with clang cannot handle a list of more than 75 tests. This shortcoming may be fixed in the future but still something to note.

**Comment by jhand2** [comment]
Agreed, the tests should not be grouped together. Additionally, I don't find the perf to really be that bad. I'll do some profiling when I get a chance but I would consider just closing this.

I have opened  #2487 to change the libc tests to behave like the libcxx tests and run each test separartely.

**Comment by jhand2** [comment]
I may have to walk back my cxx test comment. Each test takes at least 0.5 seconds and there are a lot of them, so thats pretty slow. Keeping open to investigate, but I don't want to squash them into one binary as a solution.
