### ISSUE TITLE
oeedger8r: Emit runtime type checks 

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1032]
Enclaves created on one platform can be loaded and used in another platform.
This introduces issues if the some of the types used in the EDL are different across both platforms or if the compilers on either platform pack the structs differently.

Edger8r should generate type checks to detect incompatibilities between the host and the enclave.

**Comment by anakrish** [comment]
@andschwa This is an important feature. Let me know when you want to get into this.

**Comment by johnkord** [comment]
This is for Linux/Windows interoperability

**Comment by radhikaj** [comment]
@anakrish @andschwa  Is this done?

**Comment by andschwa** [comment]
No, we prioritized this rather low because we emit compile-time warnings. This is an extension that would add runtime warnings too.

**Comment by jhand2** [comment]
What does it mean to emit runtime warnings? console log statements?

**Comment by andschwa** [comment]
I think that would be up to the implementer to decide.

**Comment by jhand2** [comment]
@anakrish can you provide a specific example of when this might happen? I'm having a hard time understanding what the actual problem is.

**Comment by andschwa** [comment]
A user might create an ELF enclave on Windows that uses types whose size is different than on Linux. While the edger8r will warn them as they produce the code for this enclave, they might ignore it. They could then take the ELF enclave to a Linux box (already built) and try to run it. They'll probably run into issues because the size of their types is different, and so this issue was to add runtime errors as well to alert the user before this happens. But you can see how it's a bit of a niche case (and requires the warnings to be ignored in the first place), so it's probably a low priority to implement.
