### ISSUE TITLE
Security: need to have to tests to make sure all the OE internal ECalls  correctly enforce memory range checking

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#1129]
We need to use oe_is_outside_enclave check against input parameters from the host
Impacted ECalls:

    OE_ECALL_INIT_ENCLAVE,
    OE_ECALL_CALL_ENCLAVE,
    OE_ECALL_CALL_ENCLAVE_FUNCTION,
    OE_ECALL_VERIFY_REPORT,
    OE_ECALL_GET_SGX_REPORT,
    OE_ECALL_VIRTUAL_EXCEPTION_HANDLER,

**Comment by anakrish** [comment]
Actually you also need to insert lfence for spectre mitigation at the right places as well.
My recommendation would be to model these ecalls in edl, generate code using oeedger8r and use the generated code as reference.

**Comment by ihaller** [comment]
While I applaud the sudden interest in the security aspects of the project, I am curious how this is different from #8. That issues was closed on the 10th of August with the message: "VVDN scrubbed the used of oe_is_outside_enclave in all existing boundary functions and fixed the remaining missing use in _HandleInitEnclave with PR #490, so closing out this task.". As far as I am aware, none of those ECALLs changed since that point in time. Were there any issues discovered in these ECALLs since that point in time?

Also for completeness sake, values returned from OCALLs (as out arguments or return values) should be subject to the same verification.

**Comment by anitagov** [comment]
>Also for completeness sake, values returned from OCALLs (as out arguments or return values) should be subject to the same verification.
@ihaller - I agree. Will extend this issue (or file a new issue) to verify values returned from OCALLs.

**Comment by johnkord** [comment]
@soccerGB Do you think you would be able to answer @ihaller 's questions here regarding the initial issue and Anand's comment? Is there anything new we need to address?

**Comment by anitagov** [comment]
Both Anand's comment and Istvan's comments need to be addressed by 2 more issues, in my opinion.

**Comment by johnkord** [comment]
Closing this as this is an ongoing responsibility.

**Comment by anakrish** [comment]
@johnkord @soccerGB  I am reopening this. We need to add tests. One of the exact functions in this list was reported as a security issue to MSRC.

**Comment by yakman2020** [comment]
We've done a pass on this. Does not appear to be an issue currently.
