### ISSUE TITLE
Support cpuid with subleaves 0-15 for leaf 4

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#1550]
Currently, OE initializes the enclave with leaves 0, 1, 4, 7 (well, it initializes more but then only allows to query those):
https://github.com/Microsoft/openenclave/blob/9b750328d29505faeb045744d23a92759d8542b1/include/openenclave/internal/cpuid.h#L29-L32

For that, it always uses a fixed subleaf of 0:
https://github.com/Microsoft/openenclave/blob/9b750328d29505faeb045744d23a92759d8542b1/host/sgx/create.c#L343-L359

And then returns -1 if another subleaf is requested for leaf 4:
https://github.com/Microsoft/openenclave/blob/9b750328d29505faeb045744d23a92759d8542b1/enclave/core/sgx/cpuid.c#L73-L84

Eigen [queries](https://github.com/eigenteam/eigen-git-mirror/blob/557f1649d5229136b01fa46c6af03dd14fed2d5f/Eigen/src/Core/util/Memory.h#L955-L985) cache sizes through cpuid by looking at leaf 4 and subleaves 0 to 15.

It would be great if OE could support the additional subleaves in leaf 4 so that Eigen can run optimally. Currently, it is necessary to disable that behavior with `-DEIGEN_NO_CPUID`.

**Comment by CodeMonkeyLeet** [comment]
@letmaik `cpuid` as implemented in OE today intentionally does not cache subleaves other than 0 for cpuid leaf 4 (in fact there was a bug fix to throw that blocking error explicitly). It primarily supports subleaf 0 for parity with the Intel SDK.

It's a feature we could consider adding, but having the OE enclave runtime cache some of this information may be undesirable in cases where the enclave application may migrate across CPU packages since `cpuid` in general is expected to be a dynamic query.

**Comment by letmaik** [comment]
@CodeMonkeyLeet Can you explain what you mean by "migrate across CPU packages"? Is that something specific to enclaves? Or are you referring to the concept of VM migration?

**Comment by CodeMonkeyLeet** [comment]
@letmaik Migration of enclaves across VM hosts is not related (enclaves are destroyed on migration anyway). This is more along the lines of NUMA awareness since there will soon be multi-package server SKUs. The same physical server node may have more than one CPU package on it, which future SGX hardware manages by creating shared secrets between the nodes. It's unclear if the CPU members of the resulting platform must be identical … in general, we've not tried to get ahead of Intel's implementation on things like CPUID for these reasons.

**Comment by prp** [comment]
SGX-LKL-PORT faces the same issue, as we need to support arbitrary `cpuid` calls inside the enclave. Currently this fails for any leaves/subleaves that are not cached/supported by OE.

**Comment by radhikaj** [comment]
@mikbras  as this is related to @prp's question and you have been driving CPUID , please take a look at this.

**Comment by jhand2** [comment]
@prp is this sufficiently supported by the ability to make an ocall to query CPUID? If so, I will close

**Comment by prp** [comment]
@jhand2 Yes, what we have in the SGX-LKL feature branch is sufficient for our needs, thanks.
