### ISSUE TITLE
Drive options on how to include submodules for 3rd party code in Open Enclave

### ISSUE THREAD

**Issue by paulcallen** [openenclave/openenclave#1902]
Today we have several third party dependencies. Currently we pull in the source into the 3rd party directory.
Taking dependencies on code that is unchanged but not doing it as a submodule seems like more work than necessary, so we need. It also makes it harder to move to newer versions of the code, or makes it harder to see that there are newer updates to the code.
There are policies that govern how to safely take in 3rd party code as submodules within Microsoft. We can do this safely and securely.
This issue to investigate this, drive the team to a consensus and move forward on the decision.

**Comment by anakrish** [comment]
Capturing my comments from #1820:

What I would prefer is the option where we can keep track of the changes we make to 3rd party code, and reapply them when we upgrade the 3rd party libraries.

The key point to keep in mind is that we don't use 3rd-party code as-is. Since the code must run within an enclave, we have to make changes to it.

Some 3rd party code like mbedtls have a nice config.h which can be edited to configure it they way we want.

Some times the changes involve directly editing code deep in the guts of the 3rd-party module (see 5e8ea11#diff-d45)

Not all changes can be upstreamed since these changes are specific to an SGX enclave.

Which of the two approaches (or some other approach) would allow us to keep track of the changes we have done to 3rd party code and automatically make sure the changes are reapplied when we upgrade the 3rd party modules?

The issue I see with the current approach is that when a 3rd party module is upgraded as in https://github.com/microsoft/openenclave/pull/1786/files, there are a large number of files to look at, it is not possible to figure out which of those files contain manual edits.
I would instead prefer the PR to just contain the set of our changes plus just a reference to the libunwind version we are upgrading to.

**Comment by anakrish** [comment]
The recent PR https://github.com/microsoft/openenclave/commit/1cd2a42585037e28a497e402ea60ac576b9128ed is a good an example that shows that our current approach to 3rdparty code (copy them into our repo and edit them) does not scale well and is error prone. In a latest update of 3rd party edger8r code, we ended up losing a set of changes needed to make edger8r frontend (maintained by intel) avoid looking for GCC on windows.

The solution for 3rd party code needs to:
- make it possible for us to change 3rd party code where appropriate
- make it easy to incorporate the (may be modified) 3rd party code built and tested via our CI
- make it easier to upstream our changes to 3rd party code

**Comment by andschwa** [comment]
@paulcallen @lilyfang Should we paste in the notes from the original discussion that were posted via email? I believe we came to a consensus then and we're at the point of figuring out how that work is going to happen.

**Comment by paulcallen** [comment]
can you make sure I have any emails on this and I will pull it together in a document

**Comment by andschwa** [comment]
@paulcallen I forwarded them your way!

**Comment by deeglaze** [comment]
The approach we take in [Asylo](https://github.com/google/asylo) is to make our build tool fetch our dependencies at a specific version/commit, perform a checksum test, and then apply any patches we distribute for that version. By distributing a patch, you can make sure you keep track of the changes you're making. A patch file can help instruct users whose codebase follows a "one version rule" for all third-party code, so that those users can integrate your changes on top of them.

In our codebase, all third-party code has to be in the global third_party subdirectory, go through license review, etc. I can't import open enclave with a musl or mbedtls subdirectory, for example. I have to refactor the code to use our repo's version.

**Comment by anakrish** [comment]
Per [SIG-Arch meeting](https://hackmd.io/KOeBDVlyQpOC-OqqHYvs0A?view#11-Aug-2020):
* Consensus is that changes that can be upstreamed should use Option 1.
   * This fork would be maintained under the OE SDK project.
   * If we maintain a fork for holding changes while upstreaming, we should be clear the fork is not intended for consumption as a standalone (i.e. we are not forking the original project).
* Any changes that we are not willing or able to upstream should reside in the OE SDK repo.
   * This is not a prescription to use patches (option 2), and could involve alternative source file inclusions, different configuration settings and introducing abstraction layers.
* A basic heuristic is:
   1. Can OE SDK consume a clone of the project with no changes to the 3rd party sources? If so, take a submodule dependency directly.
   2. If a change needs to be made, is the change something that is valuable to upstream into the 3rd party project (e.g. bug fixes, feature extension) and are we willing to do the work to upstream it? If so, fork the repo under OE SDK project and start the upstreaming process.

From: https://github.com/openenclave/openenclave/issues/3120#issuecomment-672153046
