### ISSUE TITLE
mount in enclave allow us to mount "." to "/", put then fails to open a file in pwd

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#1937]
mount(".", "/", "oe_host_file_system", MS_RDONLY, NULL) succeeds. Then fopen cert.pem fails.
Learnt from John that enclave mount does not support relative paths, in which case it would be a better developer experience if the mount fails.

**Comment by jhand2** [comment]
Is there any interest in supporting absolute filepaths? It would require an ocall to resolve the path to an absolute path but its possible (and not terribly difficult).

To make mount work properly, we should really do an ocall in mount anyway to make sure the paths actually exist (currently we do no checks).

We could also support relative paths from the other file APIs (like fopen) by again using the host to do path resolution.

If we don't want to do this, I can just add a few checks and error out if the path is relative.

**Comment by jhand2** [comment]
In all honesty, the whole mount/umount thing of hostfs seems unnecessary (you could just access the host filesystem directly) but I assume the decision was made for some reason.

@mikbras do you have an background on the decision to require mounting hostfs instead of just using it directly?

**Comment by jhand2** [comment]
*skip to the last paragraph if you don't care how hostfs works*

So it turns out that relative mount paths actually do work (sort of), just not how you would expect.

The enclave maintains it's own internal current working directory, you can query it with `oe_getcwd`. By default it is `/`, but it can be modified with `oe_chdir`. When hostfs tries to resolve relative paths, it uses `oe_realpath` which resolves by using the internal enclave current working directory without making an ocall.

Now it is a bit weird to resolve the source path using the enclave's relative path when referring to the host's filesystem, so **I'll go ahead and just forbid relative paths for hostfs as the issue initially suggests.**

**Comment by jhand2** [comment]
Addressed by #2382

**Comment by jhand2** [comment]
#2382 merged
