### ISSUE TITLE
SGX-LKL-PORT: oesign always sets SECS.MISCSELECT.EXINFO to 0

### ISSUE THREAD

**Issue by prp** [openenclave/openenclave#2118]
oesign does not permit SECS.MISCSELECT.EXINFO to be set to 1, which is necessary for an enclave to have a valid exception record for GP/PF exceptions. As a result, it is currently not possible to handle a page fault inside the enclave with the help of an OE exception handler (despite the fact that OE has a supported OE_EXCEPTION_ACCESS_VIOLATION exception type).

The fix would be to set SECS.MISCSELECT.EXINFO to 1 by default and/or make it configurable.

**Comment by yakman2020** [comment]
This is specific to SGX2.

**Comment by CodeMonkeyLeet** [comment]
Additional context:

* SGX-LKL needs POSIX signal handling for SGX-LKL (under Linux), not demand paging. In the non-OE version of SGX-LKL, this involves installing an OS signal handler that catches an in-enclave segfault outside and then relaying the exception information to the enclave (using an EENTER).

* SGX-LKL would like to handle this with the OE exception handlers, but OE SDK does not set the  SECS.MISCSELECT.EXINFO bit so it is not handled by the OE exception handlers.

* OE SDK does not enable this currently because EXINFO is only supported on SGX2 platforms as part of #GP & #PF reporting for demanding paging,  and OE SDK does not yet support SGX2. When OE SDK supports SGX2, it will be likely enabled by default for enclaves targeting SGX2, but in the meantime, SGX-LKL will need to fallback to their non-OE strategy.

**Comment by radhikaj** [comment]
@prp please let us know if we can close this issue.

**Comment by prp** [comment]
Since I did not realise that SECS.MISCSELECT.EXINFO only pertains to SGX2, and we need a solution that works with SGX1, I am closing this issue.

**Comment by radhikaj** [comment]
Thank you @prp
