### ISSUE TITLE
0.7-rc1 breaks installation on non-SGX machines

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2252]
If you use `-DUSE_LIBSGX=OFF` then on importing OE via `find_package(openenclave)` it errors with:
> CMake Error at /opt/openenclave/lib/openenclave/cmake/openenclave-config.cmake:103 (message):
  -- Looking for sgx_enclave_common library - not found

This code is faulty:
https://github.com/openenclave/openenclave/blob/abecb10d12871432b1e7ac9e4b50550b51625b2c/cmake/openenclave-config.cmake.in#L75-L109

This should have been caught by CI, please check the setup, maybe some configuration is missing.

**Comment by achamayou** [comment]
The samples are only tested agaisnt the binary package, and there is no binary package produced with -DUSE_LIBSGX=OFF as far as I can tell.

**Comment by johnkord** [comment]
Thanks for the report @letmaik!

I'd like to understand how you are using the OE SDK in this configuration so I can use it for guidance in the future! We can add a CI test case for it.

In this case, are you downloading & installing the 0.7.0-rc1 .deb package and then attempting to build an application using the cmake package with `find_package(openenclave)`?
Or did you build the OE SDK from source (setting `-DUSE_LIBSGX=OFF`) and then call `find_package(openenclave)` to find the generated openenclave-config.cmake file?

We've been operating under the assumption that a user would install the two Intel packages `libsgx-enclave-common` and `libsgx-enclave-common-dev` even on systems that don't intend to launch enclaves (including systems without SGX support).

Also, you may wish to give your comments in an open PR out right now that not only renames the USE_LIBSGX flag, but also proposes to always link libsgx_enclave_common for launching enclaves, coalescing our enclave launching behavior across platforms. Check out that PR here: https://github.com/openenclave/openenclave/pull/2250

At the core of this issue, the USE_LIBSGX=OFF flag really hasn't been supported that well so far, and we may want to change that! It's also really awkwardly named for what it does.

**Comment by achamayou** [comment]
@johnkord the assumption that all systems should have libsgx was not clear to me either. In particular, the deployment options (https://github.com/openenclave/openenclave/tree/master/scripts/ansible#open-enclave-deployment-options-via-ansible) list the "OpenEnclave Vanilla Environment" and explicitly mention that doesn't install SGX packages. It works fine too (apart from this recent cmake change), and we've had our "virtual" builds set up that way for ages.

I even remember a time when the only kit we could get (Kaby Lake) did not use libsgx, libsgx was the new thing for the shiny Coffee Lake hardware only, and -DUSE_LIBSGX=ON wasn't all that well supported at first ;)

Anyway I'll let @letmaik speak for his project, but for us this isn't a big problem, we'll just update our images and install guidelines to state that sgx packages are mandatory. I can certainly sympathise with the rationale behind #2250 and the desire to streamline the build/install path around the most useful option.

It would have been nice for this to be listed in the 0.7.0 release notes, since it is already a user-perceptible change in effect. In any case, thank you for taking the time to explain!

**Comment by letmaik** [comment]
@johnkord Makes sense. I build the OE SDK from source with `-DUSE_LIBSGX=OFF` and use `find_package(openenclave)`. This is for building a client using the hostverify library. Since the  hostverify library does not require the Intel Enclave Common library I wanted to avoid having to install it during the build. I realize though that this is only one of the annoyances and as discussed offline it should be possible to build the hostverify library with only minimal build/runtime dependencies for widest compatiblity. The latter is mostly a CMake refactoring task, so if you want to defer that to post-0.7 then that's fine with me and this issue can be closed then.

**Comment by jxyang** [comment]
@letmaik Are you working on Linux?

It has been the assumption that `sgx_enclave_common` has to be installed for building OE SDK, even on non-sgx systems. #2250 enforces this policy more cleanly.

Your case is interesting in that you are not using oehost for creating enclaves but only the host verification.  We are already building oehostverify as a standalone static library. I am not sure whether building it still requires `sgx_enclave_common` . Technically we shouldn't.

**Comment by jxyang** [comment]
@letmaik I believe #2250 will solve your problem. You just need to build OE SDK with OE_SGX=OFF. Then cmake won't look for sgx_enclave_common anymore.

**Comment by letmaik** [comment]
@jxyang Yes, I work on Linux. I'm fine with having `sgx_enclave_common` as dependency for building OE in general, but it would be very useful to be able to build the hostverify library without requiring all the regular OE dependencies. This is because it makes it unnecessarily hard to build clients on a wider range of platforms, like CentOS.

Regarding OE_SGX, this is not mentioned in the PR description. Is this a new option? What does it do exactly?

**Comment by jxyang** [comment]
@letmaik We haven't decided whether to take #2250 in v0.7, that's why it's not in the release notes.

OE_SGX was intended to separate cmake flow relevant to Intel SGX from the ones relevant to ARM TrustZone. As I read the code, I realized it could be applicable to your case which has neither Intel SGX nor ARM trustzone. It's lucky that we don't need further changes to fix your problem. John could explain more about the original intention of OE_SGX. @johnkord.

**Comment by jxyang** [comment]
It was added to deal with a build failure on TrustZone after the PR was created. I will add to the description when doing a rebase before the merge. 

Good catch on line 146. We should move it inside the `if (OE_SGX)` block. I will update the PR.

**Comment by letmaik** [comment]
As the extra build dependency to the Intel libraries was added to the changelog I'm closing this in favor of #2263.
