### ISSUE TITLE
Update bors

### ISSUE THREAD

**Issue by andschwa** [openenclave/openenclave#2318]
I keep wanting to use `bors merge` which is in the latest Bors update. Instead of updating our instance, we should swap to the bors project's public instance. @BRMcLaren @chrisrod-MSFT Want to do this tomorrow or sometime this week?

**Comment by notriddle** [comment]
It seems like you've switch from using your own hosted instance of bors onto using the publicly hosted instance.

This seems a little crazy. I'm not a Microsoft employee, and you have nothing other than my desire to maintain a good reputation to ensure that the access granted by running bors won't be abused or neglected. I've broken the public bors instance before, and left it broken for hours because *this is not my day job; there is no ops team for app.bors.tech*.

I recommend you rebuild the `oe-bors` instance from scratch, then flip over to it the same way you flipped over to `bors` in the first place. That seems like the easiest way to do it.

**Comment by andschwa** [comment]
Ah, point taken @notriddle. @BRMcLaren do you want to stand up another Bors instance and maintain it this time? The one I had setup was originally an experiment...so it was under my name and such.

**Comment by andschwa** [comment]
(For what it's worth, I read and agree with the [TOS](https://bors.tech/tos/); if we find that we really need a high SLA, we should indeed stand up our own instance, but that'll be up to @BRMcLaren et. al. to decide.)

**Comment by BRMcLaren** [comment]
@notriddle 

I understand your concerns. If anything happens, we will cross that bridge when we get there with the full understanding that this is not your day job :).

As it stands, we would prefer to continue using the public instance of bors. If we scale up, then we will rebuild our own.

**Comment by andschwa** [comment]
Closing for now. Again, if there's any issues at all, we'll stand up a (proper) instance of our own without bugging ya @notriddle. Thanks so much!
