### ISSUE TITLE
Unable to distinguish API versions

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#2336]
The master branch saw a change to the host-side quote verification library: `oe_verify_remote_report` now expects 5 arguments instead of 3 arguments in v0.7.0. We now check for `#if defined(OE_CLAIM_ID_VERSION)`, which isn't defined in v0.7.0, to tell the difference. 

It would be nice if the version number were updated when the API changes but as far as I can tell, `OE_API_VERSION` is always the same (2). Perhaps it makes sense to add separate versioning for the host-side quote verification library too?

**Comment by wintersteiger** [comment]
CC @letmaik

**Comment by radhikaj** [comment]
@gupta-ak @soccerGB request your comments on this.

**Comment by dthaler** [comment]
This is indirectly related to PR #2163, since the verify APIs are considered experimental and subject to breaking changes across releases, which is what you are observing.   As proposed in that PR, use of such APIs would require the caller to explicitly opt in to using an experimental API.   That PR does not cover how to tell what version you're opting into, so that PR should also consider the question raised in this issue.   But I think assuming there's one global "API version" is probably not sufficient to deal with experimental APIs and maybe the feature guard needs to have a version number in it.

**Comment by radhikaj** [comment]
@yentsanglee @soccerGB Please note that we have API versioning: https://github.com/openenclave/openenclave/blob/5ff92bd0c79e1b3249193d59c38ff0dc661f5640/include/openenclave/enclave.h#L261. Please use this while changing APIs.

We need more discussions for figuring out versioning for experimental and non experimental APIs. We will discuss this in CGC

**Comment by yentsanglee** [comment]
oe_verify_remote_report() has been released. We need to figure out versioning and depreciation policy going forward.

**Comment by CodeMonkeyLeet** [comment]
Per [SIG-Arch meeting](https://hackmd.io/KOeBDVlyQpOC-OqqHYvs0A?view#11-Aug-2020):
* Consensus is that Experimental APIs will not be explicitly versioned to allow development agility as is the goal of Experimental features.
* `oe_verify_remote_report` is an existing non-experimental API that predates Experimental APIs and should have been versioned per @radhikaj's comment to use the `OE_API_VERSION`
   * That API is not yet deprecated but should be in the future in favor of the currently experimental `oe_verify_evidence` APIs in the future (up to SIG-Attestation). In the meantime, we need to be vigilant that shared implementation changes do not break the existing report APIs.
