### ISSUE TITLE
CVE-2019-0117

### ISSUE THREAD

**Issue by achamayou** [openenclave/openenclave#2378]
From: https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00219.html

> Organize the code/data within enclave memory to avoid putting sensitive materials in DWORD0 and DWORD1 of cache line. The effectiveness of this mitigation is dependent on the ability for the software to avoid the affected memory region. To assist the enclave application providers to modify their code, Intel is releasing SGX SDK update (Windows version 2.5.101.3, Linux version 2.7.101.3) with new memory allocation APIs to avoid the affected memory region. More details about the APIs can be found here.

Can we expect similar mitigations to become available in OpenEnclave? If so, when?

**Comment by radhikaj** [comment]
Thanks @achamayou for reporting this. 

This CVE affects systems where Graphics is enabled. On  SGX server systems(except for the very old ones) integrated graphics is disabled. In the long term OE wants to have this mitigation in order to support client SGX systems with graphics enabled but there is no specific date in mind as yet.

In the short term, please note that Azure servers with SGX have Graphics card disabled, so are not affected by this currently.

**Comment by achamayou** [comment]
@radhikaj thank you for your quick answer. I don't know if it is easy or even possible for OE to detect if graphics are enabled, but if it is, it probably would be good to log at least a warning until the mitigation is in place. If that isn't possible, I would suggest documenting this issue.

We are only using Azure/ACC machines at the moment, so we don't need the mitigation in the short term.

**Comment by jhand2** [comment]
No issue with OE, closing
