### ISSUE TITLE
Add support for missing APIs in inttypes.h

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2538]
Add ability to call imaxabs(), imaxdiv()from enclaves.

**Comment by jhand2** [comment]
cc @CodeMonkeyLeet, @anakrish, @mikbras 

Can anyone provide color on why imaxabs and imaxdiv were listed as unsupported in the first place?

I can add them to compilation and they work fine. They don't have tests in libc-test, but there are plenty other functions in `musl/src/stdlib/` that we support but don't have tests.

**Comment by CodeMonkeyLeet** [comment]
@jhand2 The initial pass to identify the basic working set of functions was done by contractors back mid-2018, and I don't think there was much of an effort to revisit the behavior since then. The internal API surface of stdlib is inconsistent; It could have been just an oversight from Mike's initial build of libc or a choice not to support C99 features that was not enforced.

Regarding the test question, do you have other examples of functions we assert support for that are not explicitly tested? We should review them.

**Comment by jhand2** [comment]
> Regarding the test question, do you have other examples of functions we assert support for that are not explicitly tested? We should review them.

atoi, atol, bsearch, the abs functions (abs, labs, llabs), ecvt, gcvt

That's just a few, there are more. Basically half the functions in stdlib.h don't have tests.

And there may be many more across musl that don't have tests, this is just from looking in one directory.
