### ISSUE TITLE
Design of Extended Enclave Initialization Data

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#2645]
This issue is for the design discussion of the support for Extended Enclave Initialization Data. See https://github.com/openenclave/openenclave/pull/2611 for the draft implementation. The design document is available [here](https://github.com/wintersteiger/openenclave/blob/cwinter_eeid/docs/DesignDocs/ExtendedEnclaveInitializationData.md).

Summary: Upon enclave creation (`oe_create_enclave_eeid`) the enclave image is extended with additional (instance-specific) data and re-signed with the debug key. The extended data also contains the original sigstruct of the re-signed enclave image, which is verified during extended quote verification (see `common/sgx/verify_eeid.c`). This allows us to specialize enclave image during enclave creation without the need for an entirely new image and a different signing key, while maintaining security/confidentiality guarantees.

Currently open questions:
- Unclear whether a new API function is desired for enclave creation (the extra argument could also be added to the existing `oe_create_enclave`).
- Verification of EEID quotes could perhaps be done via an attestation plugin, if desired.

CC @sylvanc @ad-l @letmaik @mikbras @jxyang

**Comment by dthaler** [comment]
The design doc should be in a PR so we can generate comments against it in context.

**Comment by dthaler** [comment]
As Radhika noted in PR 2611, the guidelines say "DON'T submit changes to the public API without filing an issue and discussing with us first."  This is because until there is public review by the OE maintainers (and potentially the community at large), any implementation may need to undergo significant changes as part of the design review.   In this particular case, I do have concerns about this particular design being the best way to approach the problem from the perspective of not being SGX specific.

We want to encourage contributions so thank you for spending time on this!   I would just like to make sure design review happens in the open so we can get the best design and avoid spending lots of time on code that isn't aligned with whatever the accepted design is.   As such, in my personal opinion, I think it's too early to review PR 2611 and I would instead like to concentrate on reviewing a PR for the design doc if you can generate one quickly.

**Comment by wintersteiger** [comment]
Sure, no problem, I only opened an issue because I was asked to. This is now PR https://github.com/openenclave/openenclave/pull/2647

**Comment by dthaler** [comment]
We should keep the issue open too, I think.   (Triage meeting can verify whether to close or keep open.)

**Comment by dthaler** [comment]
I believe this issue is closely related to (but different layer from) PR #2621, and that it's important that the two layers be consistent so the designs should be reviewed together.   I also believe it's important for the designs to not be SGX-specific as I believe the stated issues are all generically applicable to any TEE.

**Comment by CodeMonkeyLeet** [comment]
Per Sig-Arch meeting, closing as resolved by the approval of design PR #2647
