### ISSUE TITLE
Enable deep copy by default

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#2693]
The recent work on refactoring the use of EDL (#2676) could benefit from the deep-copy feature in terms of security (as described in #2666). We should consider enabling the deep copy by default.

This issue is part of #1839, which tracks the progress of deep-copy feature.

**Comment by mikbras** [comment]
Some notes:
- This feature might still be considered experimental in OE.
- I think that the Intel SGX SDK only supports two-level deep copy, whereas OE tries to support multi-level deep copy (but might need more testing). This is why we did not enable it by default, at least initially.
- OP-TEE/TrustZone application must use multi-level deep copy since host memory is not automatically shared with the enclave).

**Comment by jhand2** [comment]
It's sort of already optional, right? That is, if you don't use the deep-copy macros (such as [count=n]) then you don't get deep copy.

I guess the question is what needs to be done to make this a non-experimental feature? Maybe once we run it in CI?

**Comment by dthaler** [comment]
> I guess the question is what needs to be done to make this a non-experimental feature? Maybe once more of the internal EDL functions use deep copy and we run it in CI?

I looked at the difference between public and experimental in https://github.com/openenclave/openenclave/blob/master/docs/ApiGuidelines.md  (since the deep copy macros could be said to be like an API surface area).   I see that doc doesn't explicitly state that to be non-experimental the test case(s) need to run in CI as you suggest, but I agree with you that the guidelines ought to say that explicitly.

**Comment by dthaler** [comment]
One difference in the doc is that public features must be used in at least one sample (or sample snippet), whereas that is only a recommendation not a requirement, for experimental.

**Comment by jhand2** [comment]
That's a good point. A test and use in a sample would be a good starting point to enabling this (and required by the API guidelines).

Then if we enable it in CI we can know that the code path is exercised.

**Comment by ShundaZhang** [comment]
Is deepcopy supported now **in OCall**?

I didn't see any ocall test in openenclave/tests/oeedger8r/edl/deepcopy.edl, and when I added several deepcopy tests, I got some failures when build the test application:

Added one ocall in deepcopy.edl
untrusted {
    int ocall_deepcopy_nested([in, out, count=1] NestedStruct* n);
 };

Error Log:
[ 97%] Building C object tests/oeedger8r/enc/CMakeFiles/edl_enc.dir/all_t.c.o
/home/szhan21/OE/openenclave/build/tests/oeedger8r/enc/all_t.c:15216:9: error: variable '_buffer' is used uninitialized whenever 'if'
      condition is true [-Werror,-Wsometimes-uninitialized]
    if (_ptrs == NULL)
        ^~~~~~~~~~~~~
/home/szhan21/OE/openenclave/build/tests/oeedger8r/enc/all_t.c:15361:9: note: uninitialized use occurs here
    if (_buffer)
        ^~~~~~~
/home/szhan21/OE/openenclave/build/tests/oeedger8r/enc/all_t.c:15216:5: note: remove the 'if' if its condition is always false
    if (_ptrs == NULL)
    ^~~~~~~~~~~~~~~~~~
/home/szhan21/OE/openenclave/build/tests/oeedger8r/enc/all_t.c:15226:5: note: variable '_buffer' is declared here
    uint8_t* _buffer = NULL;
    ^
1 error generated.

**Comment by mingweishih** [comment]
No, deepcopy is not supported in OCALL.
