### ISSUE TITLE
Enable app devs to use SGX simulation support on a non-SGX Windows dev machine

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2717]
A frequently asked question at a recent IETF hackathon was how to use the OE SDK on a non-SGX-capable Intel machine.   Since OE SDK supports a simulation mode, this would be highly desirable.

https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Simulation.md implies it should be doable, but that page only covers Linux, not Windows, unlike what the filename would imply.

**Comment by jhand2** [comment]
@anakrish recently enabled Simulation mode for Windows (this was not previously supported).

It looks like we need to fix up the documentation to reflect this.

**Comment by dthaler** [comment]
PR #2600 was the change to make this work, but that PR missed updating the doc.

**Comment by anakrish** [comment]
#2600 implements SGX simulation support for Windows. You can run both hardware and simulation mode on a SGX Windows machine.
However, oehost (enclave loader) still has link time dependency on Intel SGX DLLs. On a non-sgx machine, enclave loading will fail due to missing Intel DLLs (eg. sgx_enclave_common.dll, sgx_launch.dll) even though simulation mode execution is being requested. 

To fully implement the feature:
- OE SDK must delay load intel dlls only when needed via dlopen/LoadLibrary
- Simulation mode tests in CI must happen on non SGX machines. Currently they happen on SGX machines.

CC: @radhikaj  for scheduling.

**Comment by radhikaj** [comment]
#3162 and #3155 address this issue. Closing.
