### ISSUE TITLE
Outstanding issues on attestation plugin design

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2729]
There are still a number of outstanding issues on the attestation plugin design document (PR #2621), which were raised by various reviewers.  This issue is to track the issues that are still not closed.

Technical issues:
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r393247888 about "Why does this need to be in code in every application, as opposed to either (a) having all registered by default, or (b) having them be in metadata like the .conf file? I would like to minimize code that an app developer needs to write." is not yet addressed.  The only justification so far is "because the deprecated design did it that way" which is not a sufficient justification.
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r395229106 about oe_select_verifier_format is not yet addressed.
* Lines 86-88 imply that oe_get_verifier_settings() and oe_get_evidence() are called by the same app, which other parts of the doc contradict by saying the former is verifier app but the latter is attester app.
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r395229145 about not needing oe_select_attester_format() was not sufficiently addressed.   Similarly, there is no example that shows how the APIs would be used in such cases where format ID is not passed in any protocol.  As such, one cannot yet determine whether the APIs would work in such a case.
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r395354329 is not yet addressed.
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r395349038 about configuration data is not yet addressed.
* As noted in https://github.com/openenclave/openenclave/pull/2621#discussion_r395350326 the examples chosen don't seem to map to actual protocol recommendations, either in real-world scenarios or in IETF recommendations.  Instead, examples should more clearly map to actual protocol recommendations, in order to validate that the APIs would actually meet the requirements.  (For example, "Attester sends evidences of different formats until the verifier can verify" would be an anti-pattern, rather than a recommended protocol pattern.)
* The comment in https://github.com/openenclave/openenclave/pull/2621#discussion_r395343581 about local vs remote plugins is not yet addressed.

API naming issues:
* oe_register_verifier is still not changed to oe_register_verifier_plugin, so the API is not yet consistent

Editorial issues:
* A number of places refer to "attesters" rather than "attester plugins".  (E.g., "Select a format of the evidence that the registered attesters can generate")
* A number of places refer to "verifiers" rather than "verifier plugins".  (E.g., "Upon initialization, queries available verifiers")

**Comment by soccerGB** [comment]
Due to uncertainty and resource constraint, the design in PR #2621 is no longer a design YenLee and myself plan to develop for. This issue should not be considered an issue anymore from our point of view.  Thanks for your time spent on reviewing the original design

**Comment by shnwc** [comment]
Since PR #2621 has been merged, here are my comments on the outstanding issues @dthaler listed.

To help clarify my comments, I've created a document with notes on the concepts and assumptions of the OE SDK Attestation API, and posted in my fork as [Notes on OE SDK Attestation API and Plugin Library Design](https://github.com/shnwc/openenclave/blob/master/docs/DesignDocs/NotesOnAttestationAPI.md).

Technical issues:

- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r393247888) about "Why does this need” …”
  - Adding a new API function `oe_initialize_attester_plugins()` would be sufficient to address this issue
  - In my fork, there is a [definition](https://github.com/shnwc/openenclave/blob/master/include/openenclave/attestation/sgx/attester.h) and an [implementation](https://github.com/shnwc/openenclave/blob/master/enclave/sgx/attester.c) of this API function.
- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395229106) about oe_select_verifier_format …”
  - Scenario 2 should be removed, as it does not fit the attester – verifier security model as described in the [Notes](https://github.com/shnwc/openenclave/blob/master/docs/DesignDocs/NotesOnAttestationAPI.md) document.
    - For an attester to use any UUID, it needs to get optional parameters from a verifier. The attester application is not in position to decide on their own whether one opt_params is needed and what they are.
  - `oe_select_verifier_format()` does not seem a good fit, since the verifier ISV app security policy (configured by the app owner), not the OE SDK, is responsible to decide which formats it accepts.
    - Removing scenario 2 eliminate the need of this function.
  - To enable a properly configured verifier instance to discover what evidence formats are actually supported, a new function `oe_verifier_enumerate_formats()` would be needed.
- “Lines 86-88 imply that oe_get_verifier_settings() …”
  - The two functions are called by different apps, as the PR #2621 described: `oe_get_verifier_settings()` by a verifier and `oe_get_evidence()` by an attester
- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395229145) about not needing oe_select_attester_format() …”
  - Removing scenario 2 would be sufficient to address this issue.
  - Scenario 1 requires a verifier to provide a list of UUIDs and to provide the optional parameters for the selected UUID.
- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395354329) is not yet addressed.”
  - A new API `oe_initialize_verifier_plugins()` as implemented in the code file [verifier.c](https://github.com/shnwc/openenclave/blob/master/common/sgx/verifier.c) in my fork should be sufficient to address the comment. This code file also shows how `oe_sgx_get_verifier_plugins()` is implemented.
    - The existing API `oe_sgx_verifier*()`does not support dynamic list of supported verifier plugins. The new API  `oe_initialize_verifier_plugins()` supports a dynamic list.
  - ISV applications should have no need to feed configuration data to plugins. At least this is the case for SGX applications
    - If there is a need to configure, e.g. setting path to QPL or QE3. They can be set by environment variable or by host app upon startup, and not by the verifier plugin API
  - From security point of view, a verifier can be:
    - Either a host application running on a trusted OS on a trusted platform in a secure environment
      - In this case, the host-side components are considered trusted. Configuration of the host-side software stack should not have security implication
    - Or a secure enclave running on an untrusted platform
      - In this case, the verifier should only rely on enclave libraries (or another trusted enclave via secure connection) for evidence verification.
      - Any host-side software is untrusted
- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395349038) about configuration data is not yet addressed.”
  - I don’t see a need for optional configuration data for any SGX verifier.
  - In the new API `oe_initialize_attester_plugins()` and `oe_initialize_verifier_plugins()`, the interface for optional configuration data is no longer present.
- “As noted in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395350326) the examples chosen don't seem …”
  - Sorry @dthaler not sure what the your terms “customer” and “teller” mean exactly.
  - The ISV verifier software knows exactly which formats it accepts, and which optional parameters for each of the acceptable formats, as explained in the [Notes](https://github.com/shnwc/openenclave/blob/master/docs/DesignDocs/NotesOnAttestationAPI.md) document.
    - The verifier software should be built and configured so that those accepted formats and their optional parameters are supported.
    - The OE SDK provides the means for proper building and configuration of verifier software projects.
    - With proper configuration, the `oe_initilaize_verifier_plugins()` API should initialize all formats that have been built and configured to be supported
- “The comment in [#2621 (comment)](https://github.com/openenclave/openenclave/pull/2621#discussion_r395343581) about local vs remote plugin …”
  - See the “Attester – verifier security model” section in the [Notes](https://github.com/shnwc/openenclave/blob/master/docs/DesignDocs/NotesOnAttestationAPI.md) document for SGX local attestation.
  - Local attestation is a special performance optimization where:
    - The two enclaves assume that they are running on the same platform
    - They do not use heavy-weight protocols such as ECDSA or EPID
      - They don’t need any backend support either
  - As @CodeMonkeyLeet stated, when a verifier wants to use local attestation, it should already has the security policies configured to do so, and has the expectation that the attesters are on local platforms
    - Examples are the architecture enclaves (e.g. QE, PCE) in Intel SGX SDK. QE only accepts SGX report from local ISV enclaves targeted for it.
  - Other verifiers that work with attesters across platforms should be configured not to use local attestation

The API naming editorial issues look like quite straightforward to address.

**Comment by CodeMonkeyLeet** [comment]
Per SIG-arch meeting, deferring this to SIG-attestation

**Comment by yentsanglee** [comment]
Issue is covered by PR 2081 and 3168.
