### ISSUE TITLE
Testing Optimizations and Improvements Discussion

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2749]
We are hitting unacceptable limits of testing times, where users are reporting timeouts. This is due to hardware resource constraints.

We should try to find a solution to allow developers to have faster testing times.

**Comment by anakrish** [comment]
From what I understand, the only difference between Release and RelWithDebInfo builds is that the -g flag is added to the compiler in the latter. When -g is by itself supposed to not change code generation in anyway other than emitting debugging information.

Do you think we should continue testing the Release only builds in CI given that we are also testing RelWithDebInfo?

@mingweishih Are there any LVI test environments that we can get rid of?

**Comment by CodeMonkeyLeet** [comment]
I would also suggest considering moving more of the complete configuration tests into the nightly build. For example, instead of running the LVI configuration that effectively doubles the workload on all runs, we might want to consider running an LVI build for the core libraries, but not all the test binaries or executing LVI tests in the standard CI/CD job: I expect that compilation regressions are more likely to happen, rather than behavioral differences when running under LVI, so I would consider that a reasonable tradeoff.

**Comment by mingweishih** [comment]
@CodeMonkeyLeet's suggestion sounds good to me---only building the lvi-mitigated libraries without testing on normal builds, and do both on nightly. Meaning that having a flag (e.g., `LVI_MITIGATION_TESTS`) for enabling LVI-mitigation-associated tests that is decoupled from the existing `LVI_MITIGATION` flag. This should largely speed up the normal CI/CD jobs.

**Comment by BRMcLaren** [comment]
@mingweishih would you mind taking a look at this? I am unfamiliar with the LVI intricacies and you would do a much better job than I could.

**Comment by mingweishih** [comment]
If we take @CodeMonkeyLeet's suggestion on that LVI part, I can go ahead a do that.

Another open question is: should be reduce the number of configurations and move then to the nightly build?

**Comment by BRMcLaren** [comment]
@mingweishih That is a great point.

What we could do is split out the testing into two parts, one for development optimization and allow a solid foundation of testing. Then have another testing configuration that is a full blown regression test that runs periodically.
