### ISSUE TITLE
Enclave has memory leaks or memory recovery delay

### ISSUE THREAD

**Issue by yanxue-intel** [openenclave/openenclave#2776]
A memory leak occurs in the enclave when malloc/free random size memory multiple times.

test cases in [https://github.com/openenclave/openenclave/pull/2774](url)
one case is checking for 1K memory to be  malloc/free in enclave 5000000 times.
the other case is checking for random size memory to be malloc/free in enclave 5000000 times.

tests ran on Ubuntu18.04, results as follow :
===Starting malloc fixed size fragment test.
[test_malloc_fixed_size_fragment]heap size before test : 1068928.
_malloc_free_fixed_size malloc times = 5000000.
[test_malloc_fixed_size_fragment]heap size after test : 1068928.
===Starting malloc random size fragment test.
[test_malloc_random_size_fragment]heap size before test : 1068928.
_malloc_free_random_size malloc times = 5000000.
[test_malloc_random_size_fragment]heap size after test : 1048448.

**Comment by anakrish** [comment]
Thanks for identifying this!

**Comment by achamayou** [comment]
@yanxue-intel there's one leak I know of, and have come across in #2649, it's the atexit handlers. I assumed it is deliberate because the code was directly calling oe_sbrk and bypassing the debug allocator. That's been modified to use oe_nodebug_malloc, which is more explicit, but the leak remains.

It's a very small amount of memory however, much less than your test suggests is leaking, but I thought I'd point it out nonetheless.
