### ISSUE TITLE
Windows 2019 Integration Bugs and Issues

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2793]
This issue is meant for tracking the remaining Windows 2019 bugs and issues regarding integration work.

Transient failures have been noticed while [integrating](https://github.com/openenclave/openenclave/pull/2745) Windows 2019 into our CI systems. 

The error message is:

> 175: === begin _test_generate_from_private()
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\key.c:oe_private_key_sign:519]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\ec.c:oe_ec_private_key_sign:594]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\key.c:oe_private_key_sign:519]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\key.c:oe_private_key_sign:519]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\ec.c:oe_ec_private_key_sign:594]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_BUFFER_TOO_SMALL [..\..\host\crypto\bcrypt\key.c:oe_private_key_sign:519]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | BCryptImportKeyPair failed (err=0xc000000d)
> 175:  (oe_result_t=OE_CRYPTO_ERROR) [..\..\host\crypto\bcrypt\ec.c:_bcrypt_import_ec_private_key:220]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | :OE_CRYPTO_ERROR [..\..\host\crypto\bcrypt\ec.c:oe_ec_generate_key_pair_from_private:782]
> 175: 2020-04-03T12:50:46.000000Z [(H)ERROR] tid(0x1a04) | CryptExportPublicKeyInfoFromBCryptKeyHandle failed (err=0xc0000001)
> 175:  (oe_result_t=OE_CRYTest failed: ..\..\tests\crypto\ec_tests.c(210): _verify_generated_keys r == OE_OK
> 175/182 Test #175: tests/crypto/host .....................................................................................................................***Exception: Exit code 0xc0000409

This error has ~10% chance to occur, however, it seems that it can appear in a number of testing configurations

[Win2019 Sim Release Cross Compile LVI
 ](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/188/pipeline/44)

[Win2019 Sim Release Cross Compile
](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Sandbox/detail/Sandbox/1/pipeline/117)

[Win2019 Debug Cross Compile DCAP LVI](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/192/pipeline/45)

It's not consistent, and I believe is not something related to the CI or some infrastructure issue. Looking at the GitHub issues, it seems like it's related to #2617. The error code according to the [lookup](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55 ) table seems to point towards a "STATUS_INVALID_PARAMETER" parameter.

**Comment by CodeMonkeyLeet** [comment]
There are 2 different failure symptoms in the linked logs:

- On Release builds ([Win2019 Sim Release Cross Compile LVI](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/188/pipeline/44), [Win2019 Sim Release Cross Compile](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Sandbox/detail/Sandbox/1/pipeline/117)), any UCRT abort triggers a stack buffer overrun exception. (0xc0000409).
   - This truncates logging and makes it difficult to align the point of failure with the Debug build
   - Because this only happens on Release, the stack is garbled with optimizations and it’s unclear that this is the same failure as on Debug builds.
   - Based on the logging and the fact that this only seems to repro on WS2019 hosts, I will assume that the underlying root cause is the same and only discuss the next failure error.

- On Debug builds ([Win2019 Debug Cross Compile DCAP LVI](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/192/pipeline/45)), `_test_generate_from_private()` in ec_tests.c for tests/crypto/host occasionally fails to verify ECDSA signatures.
   - Specifically, it’s the same test case in that method that will trigger the failure: when the private ECDSA key is set to the P256 group order - 1
      - This is a boundary condition test, and it’s clear that the handling of this condition is slightly different on WS2019:
         - We expect that an EC private key equal to the P256 group order is illegal and should be rejected.
         - On WS2016, `BCryptImportKeyPair()` will refuse to import the key and fail at that point with `STATUS_INVALID_PARAMETER` (0xc0000009)
         - On WS2019, `BCryptImportKeyPair()` succeeds, but results in a key handle that will fail with the vague `STATUS_UNSUCCESSFUL` (0xc0000001) when we call `CryptExportPublicKeyInfoFromBCryptKeyHandle()` on it.
         - That specific test case still passes because it still ultimately results in an `OE_CRYPTO_ERROR`.
      - We expect that EC private key equal to the (P256 group order - 1) passes though, and usually it does:
         - The test uses the key (which is constant across iterations) signs a hash and verifies the resulting signature.
         - _Sometimes_ the verification of the signature fails with `STATUS_INVALID_SIGNATURE` (0xc000a000)
         - Note that EC signatures are not stable; every iteration of a sign operation can result in a different signature given the same private key and signing target.

A little additional debugging seems to indicate that this is not structural in terms of how OE SDK is invoking the underlying `BCryptVerifySignature()` function; the traces of the failure case indicate that the signature is not being rejected for any format enforcement reasons that might have changed in WS2019. Instead, it looks like the final check for the equality of the mod values is failing during ECDSA verification, so it appears that something intrinsic has changed in WS2019. The mod calculations look different when walking through the assembly in the debugger, but that's speculation not knowing how that code might have changed. 

The same signatures when saved verify successfully on Linux against OpenSSL, so this does not appear to be an existing issue in ECDSA signing. I'm marking this issue as external for follow-up with Windows, and in the meantime, I will disable this specific test on Windows (see PR #2836) to permit further testing on WS2019.
