### ISSUE TITLE
oe_terminate_enclave return OE_OUT_OF_THREADS after switchless ecall exit when TCSNUM=1

### ISSUE THREAD

**Issue by yanxue-intel** [openenclave/openenclave#2889]
test case in PR [https://github.com/openenclave/openenclave/pull/2887](url)

details as follow:
1. Create enclave with Switchless Calls and one TCS only.
2. Call empty switchless ecall, it is expected to pass.
3. Call empty ecall, it is expected to fail since TCS is occupied by trusted worker thread.
4. empty switchless ecall exit
5. Destroy enclave (this step failure, return OE_OUT_OF_THREADS)

if I replaced switchless ecall with regular ecall, test is PASS.

**Comment by radhikaj** [comment]
@mwshan @fchinchilla  please take a look at this.

**Comment by anakrish** [comment]
When an enclave worker thread has no more calls to process, it will keep spinning, checking for calls to process before doing a sleep in the host. The thread cannot sleep within the enclave because the OS's `sleep` function is not accessible within the enclave. Therefore it has to go back to the host to sleep until messages arrive.

Currently, the ecall worker threads sleep in the host by returning to the host instead of making an ocall to sleep:

https://github.com/openenclave/openenclave/blob/c92b3fcf9c77c13590b9160db34eb172a534d4a8/host/sgx/switchless.c#L82-L95

An aspect of this approach is that when the switchless ecall worker is sleeping, the enclave tcs is unbound and free, and therefore other calls (regular and switchless ecalls) may be scheduled on it.

A potential drawback of this approach is that when the enclave worker, after sleeping in the host, wakes up and has to go back into the enclave via an ecall, there may not be a tcs available for it.

We could achieve a strong binding between an ecall worker and its tcs by doing an ocall to sleep instead of returning. The implication of such a change is that there must be atleast one tcs reserved for regular calls so that the enclave can be terminated. Therefore enclaves with just one tcs may not have any switchless ecall worker threads.

**Comment by MWShan** [comment]
Can you use an OCall to sleep and add a switchless ECall to terminate the enclave?

**Comment by anakrish** [comment]
@MWShan Great suggestion. I have a PR in which the enclave worker thread sleeps via OCALL rather than returning: #2929

In another PR #2927, I have fixed the ordering in enclave termination. First switchless manager 
(threads) will be stopped, and then the destructor will be called inside the enclave. 

Since switchless manager terminates first, any running ecall worker threads would also exit, freeing up the sole tcs which can be used to invoke the destructor ecall.

**Comment by CodeMonkeyLeet** [comment]
Per [SIG-arch meeting](https://hackmd.io/KOeBDVlyQpOC-OqqHYvs0A?both#12-May-2020), removing from SIG-arch project tracking as a implementation-level investigation that can be brought back to SIG-arch if the resulting proposed resolution requires an architectural change.
