### ISSUE TITLE
Directory openenclave/tests/libcxxrt/results and its contents should not be in repository

### ISSUE THREAD

**Issue by shnwc** [openenclave/openenclave#3095]
The directory contains test logs, and should not have been committed to the repository.
https://github.com/openenclave/openenclave/tree/master/tests/libcxxrt/results

**Comment by jhand2** [comment]
They are used by the libcxxrt tests to check for expected output.

See CMakeLists.txt file:

```
add_test(
      NAME tests/libcxxrt/${name}-diff
      WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
      COMMAND
        ${OE_BASH} -c
        "./host/libcxxrt_host ./enc/libcxxrttest-${name}_enc > ${name}_output.log 2>&1 &&
            diff ${name}_output.log ${RESULTDIR}/exp_${name}_output.log")
```

**Comment by mingweishih** [comment]
The mean reason is that we directly use the original test cases from the libcxxrt repo instead of re-implementing them.  On Linux, we could build those test cases on both host and enclave, and then compare their output. However, we cannot not build them on Windows. That's why we end up having these logs.

**Comment by shnwc** [comment]
@jhand2 @mingweishih thank you for your explanation! Hopefully eventually we can have a more elegant solution. I'll close this issue.
