### ISSUE TITLE
_get_attester_plugins: buffer overread after ocall

### ISSUE THREAD

**Issue by douglasmaciver** [openenclave/openenclave#3500]
Returned buffer size is not validated against supplied buffer size, resulting in a potential buffer overread into enclave heap.  Out-of-bounds memory is copied safely into enclave heap due to memory allocation being based on host-reported buffer size. Full exploitability undetermined, but risk thought to be low.

https://github.com/openenclave/openenclave/blob/5a85b33476f94eebd57a7abdd34bd7584efeb348/enclave/sgx/attester.c#L374-L384

**Comment by douglasmaciver** [comment]
Refinement of original post: The problem is with line 384, where the `uuid_count` is computed based on the `temporary_buffer_size` returned by the host.

**Comment by ryanhsu19** [comment]
The value of `temporary_buffer_size` is obtained in lines 357 and 358, and in `oe_sgx_get_supported_attester_format_ids()` in `host/sgx/sgxquote.c`, which can be reached from `oe_get_supported_attester_format_ids_ocall()` (the function mentioned in this issue), it raises an `OE_BUFFER_TOO_SMALL` error if it requires more space to allocate.

Since it has been validated in lines 357 and 358, `OE_OK` should be expected in lines 374-384, with `result` and `retval` both being checked. The `&temporary_buffer_size` can be replaced with `NULL` in line 378. What do you think?
