### ISSUE TITLE
oe_get_report returns 512 x (0xFF)

### ISSUE THREAD

**Issue by specio** [openenclave/openenclave#4024]
Hi,
I'm trying to get SGX quote(report) from an enclave.

```
int enclave_get_quote(uint8_t **quote, size_t  *quote_size, uint8_t** pem_key, size_t* key_size)
{
    uint8_t sha256[32];
    uint8_t pem_public_key[512];
    uint8_t* key_buf = NULL;

    crypto.retrieve_public_key(pem_public_key);
    crypto.Sha256(pem_public_key, sizeof(pem_public_key), sha256);

    oe_result_t result;
    *quote = (uint8_t*)oe_host_malloc(OE_MAX_REPORT_SIZE);
    *quote_size = OE_MAX_REPORT_SIZE;
    result = oe_get_report(OE_REPORT_FLAGS_REMOTE_ATTESTATION, sha256, sizeof(sha256), NULL, 0, *quote, quote_size);

    key_buf = (uint8_t*)oe_host_malloc(512);
    memcpy(key_buf, pem_public_key, sizeof(pem_public_key));

    *pem_key = key_buf;
    *key_size = sizeof(pem_public_key);
    return result;
}
```
Enclave is created with:

  ```
 oe_result_t result;
    uint8_t* quote;
    size_t size = 0;
    result = oe_create_enclave_enclave(path, OE_ENCLAVE_TYPE_SGX, OE_ENCLAVE_FLAG_DEBUG, NULL, 0, enclave);
```

Getting pub_key works fine:
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjRmq7K2knUt+GtBEFfId
...
...
QwIDAQAB
-----END PUBLIC KEY-----
```
I'm using own attestation based on raw sgx quote, so I'd prefer to get that report, rather than moving to get_evidence API.
This code is 2yo and was based on remote_attestation sample. Sample switched to get_evidence, but i guess oe_get_report is still supported.
Therefore I can't attest with this report, I have no idea why this method is:
returning oe_result_t: 0
setting report size to: 4600
filling buffer with 0xFF's

Regards,
Szczepan

**Comment by qiucwang** [comment]
Hi @specio ,

Could you share more context of the issue. Looks like you were calling `oe_get_report()` from the enclave side and it succeeded (oe_result_t = 0 and report size = 4600) but the report was not written to the buffer?

[Here](https://github.com/openenclave/openenclave/blob/master/include/openenclave/enclave.h#L296) is API header, could you try to pass `quote` instead of `*quote`? If that still not work, tried to create a `uint8_t* tmp_quote_buffer` in the enclave and output report content to this buffer. Then call `oe_memcpy_s` to copy the report content from `tmp_quote_buffer` to `quote` which is allocated by `oe_host_malloc`. You can take a reference [here](https://github.com/openenclave/openenclave/blob/v0.10.x/samples/remote_attestation/common/dispatcher.cpp#L88-L98).

Since `oe_get_report` is a legacy API, we still recommend switch to [oe_get_evidence](https://github.com/openenclave/openenclave/blob/master/include/openenclave/attestation/attester.h#L106) which is capable to [generate a raw SGX quote](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Attestation_API_Proposal.md). With format ID `OE_FORMAT_UUID_SGX_ECDSA`, the evidence looks like `[oe_attestation_header] || SGX_ECDSA_quote(hash) || custom_claims_buffer`. And you can unset the `OE_EVIDENCE_FLAGS_EMBED_FORMAT_ID` bit in its `flags` parameter to opt out the `oe_attestation_header` and pass a `NULL` custom_claims_buffer.

**Comment by yentsanglee** [comment]
@specio `oe_get_report()` internally allocates memory for the report. Please refer to SDK document [oe_get_report_v2](https://openenclave.io/apidocs/v0.15/enclave_8h_aefcb89c91a9078d595e255bd7901ac71.html) and [oe_free_report](https://openenclave.io/apidocs/v0.15/enclave_8h_acd119f88c4005f9c130f6f78b9ae43e0.html#acd119f88c4005f9c130f6f78b9ae43e0).

**Comment by specio** [comment]
Sample from version 10.x was very helpful, it worked.
Thanks.
