### ISSUE TITLE
OE-Fuzzing: Crash detected in /host/sgx/loadelf.c

### ISSUE THREAD

**Issue by mrragava** [openenclave/openenclave#4056]
==5173==ERROR: AddressSanitizer: SEGV on unknown address 0x7f3c74abf1f0 (pc 0x0000006fc3b5 bp 0x7fffcf8885d0 sp 0x7fffcf8883c0 T0)
==5173==The signal is caused by a WRITE memory access.
    #0 0x6fc3b4 in _set_uint64_t_dynamic_symbol_value /openenclave/host/sgx/loadelf.c:724:5
    #1 0x6f2cad in _patch_elf_image /openenclave/host/sgx/loadelf.c:928:5
    #2 0x6ae3e4 in _patch /openenclave/host/sgx/loadelf.c:1174:5
    #3 0x670089 in oe_sgx_build_enclave /openenclave/host/sgx/create.c:929:5
    #4 0x67e76a in oe_create_enclave /openenclave/host/sgx/create.c:1159:5
    #5 0x58f805 in oe_create_create_enclave /src/dynamic/fuzzing/create/host/create_u.c:7291:12
    #6 0x58028e in CreateEnclave(char const*) /../../src/dynamic/fuzzing/create/host/host.cpp:45:14
    #7 0x5810b5 in LLVMFuzzerTestOneInput /../../src/dynamic/fuzzing/create/host/host.cpp:131:19
    #8 0x4577ba in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
    #9 0x4583f5 in fuzzer::Fuzzer::TryDetectingAMemoryLeak(unsigned char const*, unsigned long, bool) /compiler-rt/lib/fuzzer/FuzzerLoop.cpp:608:3
    #10 0x44bed9 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /compiler-rt/lib/fuzzer/FuzzerDriver.cpp:281:6
    #11 0x45095b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /compiler-rt/lib/fuzzer/FuzzerDriver.cpp:709:9
    #12 0x4759f2 in main /compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #13 0x7f3c79d8ebf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #14 0x42dab9 in _start (/home/ragava/Desktop/labs/crashes/create/_patch_elf_image/create_host+0x42dab9)

**Comment by mrragava** [comment]
[_patch_elf_image.zip](https://github.com/openenclave/openenclave/files/6570140/_patch_elf_image.zip)
Extract the archive and execute run.sh to reproduce the crash.

**Comment by douglasmaciver** [comment]
While we focus on the obvious importance of Enclave security, we must not forget that host-side component security is important to the host's well-being --- we don't want a host app built with the Open Enclave SDK to be a threat vector against the host.

I took a quick look at the code and my guess is that the fault is caused by insufficient integer overflow detection and assert-based bounds-checking in `loadelf.c.` For secure code, offset and pointer calculation must be protected from overflow, and bounds checking must be done in all builds, not just debug/testing.
