### ISSUE TITLE
support sysconf _SC_PAGESIZE and _SC_PHYS_PAGES

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4123]
can we know  the enclave's physical memory infomation(page_size or sc_physical_page) in runtime please?

**Comment by anakrish** [comment]
Currently OE provides a dummy implementation that always returns -1
https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/libc/sysconf.c#L8-L13

We need to see if we can use the MUSL implementation instead.

**Comment by radhikaj** [comment]
SGX always requires a 4K page size. 
Would it be possible @superajun-wsj to try out the approach @anakrish mentions above?
Q: Is this SGX specific?

**Comment by superajun-wsj** [comment]
> SGX always requires a 4K page size.
> Would it be possible @superajun-wsj to try out the approach @anakrish mentions above?
> Q: Is this SGX specific?

yes, it's sgx specific. we have an application runs based on sgx's enclave, and the application needs to know how many physical memory size could be used in runtime. If we use musl's implementation, it may get host side physical memory size, while it's not we expected.

**Comment by hyunsooda** [comment]
Hi @superajun-wsj, I have just a question from your comment.
I couldn't understand your need to identify the usable physical memory size **at runtime**, not the **enclave launch time** unless you should do something like exquisite memory scheduling. As far as I know, all the information related to memory including the physical memory information is not managed in the SGX microcode and these tasks are fully delegated to OS. I guess this question is similar to "how can I get trust time without querying to OS?"

As far as I know, the enclave memory size is determined at launch time by looking memory size value in the configuration. Sometimes I had a bad experience when I add some data and workload into the enclave since it aborts segfault due to the memory size. So I increase the memory size and test it again until to find an appropriate memory size.

**Comment by anakrish** [comment]
@superajun-wsj 

As @hyunsooda pointed out, the enclave heap size is part of the enclave configuration.
https://github.com/openenclave/openenclave/blob/eaa3880f2d2b05c7713b7b1b31258c4147ee2280/samples/helloworld/enclave/helloworld.conf#L6

If you want to know *approximately* how much of the enclave heap has been used, then you can use the [oe_allocator_mallinfo](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Mallinfo.md) api to query the max, current, and peak heap sizes.

**Comment by superajun-wsj** [comment]
> Hi @superajun-wsj, I have just a question from your comment.
> I couldn't understand your need to identify the usable physical memory size **at runtime**, not the **enclave launch time** unless you should do something like exquisite memory scheduling. As far as I know, all the information related to memory including the physical memory information is not managed in the SGX microcode and these tasks are fully delegated to OS. However, [you may see the heap(EPC memory) state managed by OE](https://github.com/openenclave/openenclave/issues/3728). I guess this question is similar to "how can I get trust time without querying to OS?"
> 
> As far as I know, the enclave memory size is determined at launch time by looking memory size value in the configuration. Sometimes I had a bad experience when I add some data and workload into the enclave since it aborts segfault due to the memory size. So I increase the memory size and test it again until to find an appropriate memory size.

Thanks very much for your professional response.  We need to know the enclave's physical memory size to decide how much memory we will allocate to do heap memory's second management.

**Comment by superajun-wsj** [comment]
> @superajun-wsj
> 
> As @hyunsooda pointed out, the enclave heap size is part of the enclave configuration.
> https://github.com/openenclave/openenclave/blob/eaa3880f2d2b05c7713b7b1b31258c4147ee2280/samples/helloworld/enclave/helloworld.conf#L6
> 
> If you want to know _approximately_ how much of the enclave heap has been used, then you can use the [oe_allocator_mallinfo](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Mallinfo.md) api to query the max, current, and peak heap sizes.

Thank you so much. I think `oe_allocator_mallinfo` is what we need, it can help us. Thank you again.

**Comment by DylanWangWQF** [comment]
Hi, @hyunsooda 
I have a question from your comment. Sry for my noise.
> As far as I know, the enclave memory size is determined at launch time by looking memory size value in the configuration. Sometimes I had a bad experience when I add some data and workload into the enclave since it aborts segfault due to the memory size. So I increase the memory size and test it again until to find an appropriate memory size.

In my case, the enclave image is already around 50M. Since EPC paging is available in Linux, I set the large heap size which exceeds the EPC size(128MB, ~90MB). At runtime, my code will create some class objects which may exceed the remained enclave memory. In doing so, it will swap EPC page, right? (swapping will be expensive)

I also receive the `segfault` when running the sample code.

**Comment by hyunsooda** [comment]
Hi @DylanWangWQF, I don't have much professional knowledge.
As far as I know, the enclave memory can be larger than 128MB or 256MB which are the maximum memory size in almost all hardware with SGX1. This is because the virtual memory size is really huge, so there is no problem in swapping in theory, but it will introduce swapping overhead. So, I guess that we should not encounter segfault even the memory size is much smaller in the configuration file. The quick check of this is that we can run the same implementation on the pure SGX SDK, not the OE, and see that there is segfault in there. I didn't try this yet. If this hypothesis is correct, I guess that OE's internal memory management (libc) may have something related to this since it's a different implementation between SGX SDK's libc and OE's libc. The correct answer may come from OE's maintainers.

**Comment by radhikaj** [comment]
Closing this since the original question is answered.
@DylanWangWQF, can you please open a new issue for the question you had regarding the segfault above?
