### ISSUE TITLE
Enclave access the class variable which is stored in the hosr memory

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4125]
Hi, team.
I  run a program, a class variable is generated and stored in the host memory.
In this case, is it available for the enclave to access this class variable to do the following operations?
Is there a similar sample about this?

**Comment by anakrish** [comment]
C++ objects cannot be **reliably accessed** across the enclave/host boundary. To access the C++ object in a typed manner (instead of untyped void* ), the enclave must also compile in the definition for the class. Since the C++ libraries used by the host and enclave are different, the host definition and enclave definition won't be binary compatible. Virtual functions in the class would make it even harder for the object to be used within the enclave.

Instead, it is preferable to:
- Use EDL to marshal the object to the enclave and use it. This is better for security since it prevents TOCTOU attacks by the host.
- Or define a C struct and share that between host and enclave. For shared variables between host and enclave, the enclave author must manually mitigate against various attacks.

**Comment by DylanWangWQF** [comment]
@anakrish 
Thanks for your reply!
In HElib, it provides the function to write the `Context` object to stringstream, and read from the stringstream to reconstruct the object;
As we discussed before,
```
std::stringstream ss;
context.writeTo(ss);   //wrtite
helib::Context newContext = helib::Context::readFrom(ss); //read and construct
```
Is this operation available based on your above comment? `newContext` is a class object (constructor).
Now, something is wrong in `helib::Context newContext =`, assign the object to he `newContext`

**Comment by anakrish** [comment]
@DylanWangWQF 
> std::stringstream ss;
context.writeTo(ss);   //wrtite
helib::Context newContext = helib::Context::readFrom(ss); //read and construct

If the above code is executed within the enclave, then no host memory is involved. 

Can you provide reproduction steps/scripts to help investigate problem with newContext.

**Comment by DylanWangWQF** [comment]
execute within the enclave, consider to assign more heap pages.
Close this issue
