### ISSUE TITLE
Link Error while compiling sample

### ISSUE THREAD

**Issue by joydddd** [openenclave/openenclave#4128]
Hi, I have undefined reference errors when I was trying to run samples. I believe it's due to some library I didn't install but I don't know which. Could you help me with this? 
Here is the command: 
```
gcc -o sample_enc sample_t.o enc.o -L/opt/openenclave/share/pkgconfig/../../lib/openenclave/enclave -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--export-dynamic -Wl,-pie -Wl,--build-id -Wl,-z,noexecstack -Wl,-z,now -Wl,-gc-sections -loeenclave -loelibc -loesyscall -loecore
```
Error msg: 
```
/usr/bin/ld: /opt/openenclave/share/pkgconfig/../../lib/openenclave/enclave/liboeenclave.a(link.c.o):(.data.oe_link_enclave.symbols+0x28): undefined reference to `oe_crypto_initialize'
/usr/bin/ld: /opt/openenclave/share/pkgconfig/../../lib/openenclave/enclave/liboeenclave.a(report.c.o): in function `oe_verify_raw_sgx_report':
/source/openenclave/enclave/sgx/report.c:69: undefined reference to `oe_aes_cmac_sign'
```
and more. 
I'm running on ubuntu 18.04 LTS in simulation mode.

**Comment by anakrish** [comment]
@joydddd The crypto library need to be specified as well - oecryptombedtls or oecryptoopenssl

**Comment by joydddd** [comment]
Thanks a lot. But I still get the same errors after adding these two flags to my Makefile. I'm trying to run a demo from Jordan https://github.com/jhand2/oe-sample-oss2020, `make all` in the enclave folder. The flags are generated from `pkg_config oeenclave-gcc --libs`.

**Comment by anakrish** [comment]
@joydddd 
OpenEnclave has evolved since Jordan's demo. System OCALLs have been [refactored](https://github.com/openenclave/openenclave/blob/master/docs/SystemEdls.md) have been refactored so that the enclave author can selectively opt into system ocalls.

`oe_sgx_get_cpuid_table_ocall` is defined in the following EDL that you need to import:
https://github.com/openenclave/openenclave/blob/b7ef81ef772bc3d0ebfaa47c596b887cb16604c8/include/openenclave/edl/sgx/cpu.edl#L19-L21


The helloworld sample would be a good starting point for playing with OE SDK. It's EDL imports platform.edl which internally imports cpu.edl:
https://github.com/openenclave/openenclave/blob/b7ef81ef772bc3d0ebfaa47c596b887cb16604c8/samples/helloworld/helloworld.edl#L6

The following document is a good starting point for setting up an SGX machine:
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md

**Comment by joydddd** [comment]
Thanks a lot. The helloworld demo runs perfectly.
