### ISSUE TITLE
zlib support in openenclave

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4244]
Some application in enclave need to call inflate and crc32 function from zlib,  is it possible that openenclave support them in sgx please?

**Comment by anakrish** [comment]
`oeapkman`, now available in master, makes it easy to use static libraries like `zlib` within enclaves.

The master branch has a test for using `zlib` within an enclave, and a sample for using `sqlite` as well.
https://github.com/openenclave/openenclave/tree/master/tests/tools/oeapkman/zlib/enc

Once you install the libraries via `oeapkman`
https://github.com/openenclave/openenclave/blob/e1082fa890986416df23899b565a88dbbe3217d8/tests/tools/oeapkman/zlib/enc/CMakeLists.txt#L24

then you can specify the header file paths as well as link against the library:
https://github.com/openenclave/openenclave/blob/e1082fa890986416df23899b565a88dbbe3217d8/tests/tools/oeapkman/zlib/enc/CMakeLists.txt#L31-L34

See, https://github.com/openenclave/openenclave/blob/master/samples/apkman/README.md for further details on how to use `oeapkman`.

I'm in the process of creating a separate repository to showcase the use of various libraries (e.g: curl, gmp, protobuf etc) via `oeapkman`. That repository will demonstrate using prebuilt versions of the libraries as well as building libraries from source so that can be fine-tuned for enclave use.

**Comment by radhikaj** [comment]
@superajun-wsj  Please look at samples above and reopen if you have any new questions.
