### ISSUE TITLE
Examples of vulnerabilities (CVEs) mitigated by the file encryptor use case

### ISSUE THREAD

**Issue by Zildj1an** [openenclave/openenclave#4258]
Are there any examples of CVEs mitigated by the file encryption sample use case (by using the mbedTLS library)?

**Comment by radhikaj** [comment]
File encryption is a basic security feature and prevents secrets being leaked to the host.

**Comment by radhikaj** [comment]
@Zildj1an please let us know if you have specific questions as follow ups.

**Comment by Zildj1an** [comment]
So you are not familiar with any concrete CVE(s) that the File encryptor could mitigate?

**Comment by mingweishih** [comment]
> So you are not familiar with any concrete CVE(s) that the File encryptor could mitigate?

Can you elaborate a bit on using "file encryption" to mitigate CVEs? What type of CVEs are you thinking of?

File encryption is really a general approach to ensure the confidentiality of a file when saving on the disk. By using this along with TEE, one can get the combination of "data-in-use" and "data-at-rest" protection, especially against the untrusted host in the threat model of TEE.

**Comment by Zildj1an** [comment]
Thanks for the info @mingweishih I didn't have any particular type of CVEs in mind, but I was wondering if there are any good examples of vulnerabilities to mitigate. I came across CVE-2019-11064 and CVE-2018-6975, but perhaps you had better examples :)

**Comment by mingweishih** [comment]
"file encryption" with TEE is a general security practice that reinforces the TEE use case instead of mitigating a specific vulnerability. I personally don't think it makes sense to find CVEs for such practices, which is similar to the question of "what CVEs mitigated by TLS connections?". Closing this issue for now, feel free to reopen if you have more specific question in mind.
