### ISSUE TITLE
Build tools individually

### ISSUE THREAD

**Issue by Zildj1an** [openenclave/openenclave#4265]
I would like to compile the tools individually, but (for example) there is no Makefile inside /openenclave/tools/oesign. Could someone point me in the right direction?

**Comment by mingweishih** [comment]
OE uses cmake build system instead of make. Makefiles are automatically generated via the cmake command.  After that, you can use `make <cmake target>` to build a target individually. The following example shows how to build `oesign` tool:

```
mkdir build
cd build
cmake ..
make oesign
```

For more information, please consult cmake documentation.

**Comment by radhikaj** [comment]
@Zildj1an, please reopen if you you have problems with building.
