### ISSUE TITLE
`std::mutex` implementation is broken

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#4555]
`std::mutex` can be locked multiple times in succession in OE SGX enclaves.

Minimal repro is something like this:

```diff
diff --git a/tests/threadcxx/enc/enc.cpp b/tests/threadcxx/enc/enc.cpp
index f116c9051..0f2f10b96 100644
--- a/tests/threadcxx/enc/enc.cpp
+++ b/tests/threadcxx/enc/enc.cpp
@@ -56,6 +56,16 @@ static std::atomic<size_t> test_mutex_count2(0);
 
 void enc_test_mutex_cxx()
 {
+    {
+        std::mutex mut;
+        mut.lock();
+        mut.lock();
+        if (mut.try_lock())
+        {
+            abort();
+        }
+    }
+
     std::stringstream ss;
 
     recursive_mutex1.lock();
```

Obviously the second `mut.lock()` should block (it doesn't), and a subsequent `try_lock()` should fail (it succeeds).

**Comment by radhikaj** [comment]
Thanks for reporting this @eddyashton. Is this is a regression in behavior or would you say it is a long standing issue?

**Comment by eddyashton** [comment]
As far as I can tell, it's a long-standing issue - it's the same in `v0.17.0`, and I haven't gone through the hoops to build any releases from before that.

**Comment by eddyashton** [comment]
Investigating a little further, it looks like the `pthread_spin_*` functions work as expected, but the `pthread_mutex_*` functions do not.

So this blocks:
```
    {
        int ret;
        std::cout << "About to test spinlock" << std::endl;
        pthread_spinlock_t sl;
        std::cout << "Constructed spinlock" << std::endl;
        ret = pthread_spin_init(&sl, PTHREAD_PROCESS_PRIVATE);
        std::cout << "init returned " << ret << std::endl;
        ret = pthread_spin_lock(&sl);
        std::cout << "lock returned " << ret << std::endl;
        ret = pthread_spin_lock(&sl);
        std::cout << "lock again returned " << ret << std::endl;
        ret = pthread_spin_trylock(&sl);
        std::cout << "trylock returned " << ret << std::endl;
        if (ret == 0)
        {
            abort();
        }
        pthread_spin_unlock(&sl);
        pthread_spin_destroy(&sl);
    }
```

Whereas this doesn't block, and reaches the `abort()`:
```
    {
        int ret;
        std::cout << "About to test mutex" << std::endl;
        pthread_mutex_t m;
        std::cout << "Constructed mutex" << std::endl;
        ret = pthread_mutex_init(&m, nullptr);
        std::cout << "init returned " << ret << std::endl;
        ret = pthread_mutex_lock(&m);
        std::cout << "lock returned " << ret << std::endl;
        ret = pthread_mutex_lock(&m);
        std::cout << "lock again returned " << ret << std::endl;
        ret = pthread_mutex_trylock(&m);
        std::cout << "trylock returned " << ret << std::endl;
        if (ret == 0)
        {
            abort();
        }
        pthread_mutex_unlock(&m);
        pthread_mutex_destroy(&m);
    }
```

**Comment by hal-ler** [comment]
The underlying oe_mutex is a recursive mutex implementation with no option to disable the recursive semantics.
As a consequence, pthread_mutex_lock implements the correct semantics only for `PTHREAD_MUTEX_RECURSIVE` and not the others (such as `PTHREAD_MUTEX_DEFAULT`).
`std::mutex` is also explicitly stated in the standard as: `mutex offers exclusive, non-recursive ownership semantics`.
Only `std::recursive_mutex` should offer recursive semantics.

**Comment by eddyashton** [comment]
The `LibcSupport.md` doc claims that the `pthread_mutexattr_*` functions are supported. But [they all forward](https://github.com/openenclave/openenclave/blob/e6f488688f14466c49000eb1105c8f59ff85474e/include/openenclave/corelibc/bits/pthread_mutex.h#L10) to `oe_pthread_mutexattr_*` functions which are [implemented as noops](https://github.com/openenclave/openenclave/blob/e6f488688f14466c49000eb1105c8f59ff85474e/enclave/core/pthread.c#L142), so there is no way to set an attribute requesting a non-recursive implementation, and [nothing in the implementation](https://github.com/openenclave/openenclave/blob/e6f488688f14466c49000eb1105c8f59ff85474e/enclave/core/sgx/thread.c#L159) tracking attributes to offer the non-recursive behaviour.

**Comment by achamayou** [comment]
@anakrish whenever possible, I would prefer for libcxx to behave in enclave in the same way that it does elsewhere. That's the least amount of surprise for users, which I think is a sound principle. That means deadlock in this case, but logging is definitely a welcome addition.

@mikbras I had interpreted this statement:

> There is a strong case for ignoring and closing this issue since the C++ standard is inconclusive and the dominant implementations [...] are in disagreement.

to mean that there was a strong case for deliberately keeping `std::mutex` recursive. The logical connection between the facts (lack of standard clarity, different implementations) and the conclusion (picking a third behaviour, not described in the standard) is what I did not and still do not understand.

My statement was hypothetical ("would lead"), because I think we are still discussing the change, rather than past ("decided to choose").

**Comment by mikbras** [comment]
> My statement was hypothetical ("would lead"), because I think we are still discussing the change, rather than past ("decided to choose").

@anakrish: Oh, how interesting. I'm glad I asked for clarification and that this was just a misunderstanding. Sometimes we Americans use the  word "would" with a present tense verb to refer to a past event as in "Why would he do that?" (upon learning what one has done in the past). The confuse matters more, American dictionaries generally define "would" as the past tense of "will" (https://www.merriam-webster.com/dictionary/would). In my leisure I will research the word as used in the OED.

As for this issue, I already agreed that OE should deadlock under these circumstances, but I maintain that there is a strong case against this course of action because I try to be objective and think about an issue from all points of view.

I reviewed your quotations from the C++ Working Draft I am still not convinced that the document is prescribing deadlock as an implementation option because of the use "may deadlock". Traditionally, normative documents are careful about using the term "shall" when being prescriptive and they tend to use "may" when being descriptive (to describe what may or may not happen). The document mixes the use of these terms, which is confusing and inconclusive in my view.

In my opinion, the implementation should throw an exception as you noted above, but I did not suggest it since it is misaligned with **libcxx**. I would have preferred a strong statement from the document like "shall throw an exception".

**Comment by achamayou** [comment]
@mikbras I can see that my sentence is ambiguous, depending on whether "would" is interpreted as being the past, or conditional form of "will" (I meant the latter in this case!). I should probably have worded my sentence differently, sorry!

I absolutely agree that the document is not clearly prescriptive about this situation, which is why I used "suggest" and "may" above the quotations. I think the mention of deadlock and throw makes either of them a justifiable implementation choice, but I find no statement that supports making `std::mutex` equivalent to `std::recursive_mutex`. The existence of the two separate types should, in my opinion, specifically rule out the particular implementation choice of making them equivalent.

I suspect the intention of the standard is that implementations that can detect this at no cost should throw, and I agree with you that it probably is the most user-friendly choice in the absence of context. In this case though (port of libcxx in an enclave environment), the least surprising thing to do is arguably to leave the behaviour of libcxx unchanged.

I do try to be objective too, and to be clear I would be fine with throwing or abort, even though they're not my preference in this context. I would not (conditional!) find making all `std::mutex` recursive acceptable, because of 33.4.3.2.1.1 `The class mutex provides a *non-recursive* mutex with exclusive ownership semantics` (emphasis mine).

**Comment by mikbras** [comment]
> @mikbras I can see that my sentence was ambiguous, depending on whether "would" is interpreted as being the past, or conditional form of "will" (I meant the latter in this case!). I should probably have worded my sentence differently, sorry!

@achamayou No worries at all. Just a simple misunderstanding probably due to Americanisms. 

I can see now why you interpret the document the way you did and I can respect that. My guess is that when they say "may deadlock" they are describing what the underlying layer may (or may not) do. For example, POSIX threads deadlock whereas Windows mutexes detect the deadlock condition. To put this in context, the ``std::mutex`` implementation was prototyped over POSIX threads before the standard was ever drafted. It seems the document defers to the underlying implementation and views ``std::mutex::lock`` as a wrapper for that implementation. Taken as such, all their hedging around what it may do is understandable. When taken descriptively, "may deadlock" also allows for the possibility that it may not deadlock if you take "may" to mean "might" rather "permitted to" (another English usage conundrum for another day). I concede that we should pick one of these two behaviors but only for practical consistency, but I think that not all ambiguity has been removed, although discussing this with you has helped refine my understanding of the problem.

I see what you are saying about ``std::mutex`` and ``std::recursive_mutex`` implying something about the behavior of ``std::mutex::lock`` but my view is that an underlying recursive mutex satisfies both interfaces when a program is correct in the formal sense. It is only when it is incorrect that the question about ``std::mutex::lock`` arises, which is why I believe it is better to detect and report incorrect usage rather than deadlock on it. But since we are trying to match the POSIX threads implementation, I am fine with a deadlock.

**Comment by mikbras** [comment]
@achamayou: yes, I think we are in agreement. Thank you for helping me understand your position better.
