### ISSUE TITLE
Use /dev/sgx_enclave instead of /dev/sgx/enclave

### ISSUE THREAD

**Issue by the729** [openenclave/openenclave#4668]
OE uses the SGX driver with device nodes `/dev/sgx/{enclave, provision}`. 

However, according to [SGX Installation Guide from Intel](https://download.01.org/intel-sgx/sgx-dcap/1.11/linux/docs/Intel_SGX_SW_Installation_Guide_for_Linux.pdf), page 5, the latest device nodes should be `/dev/{sgx_enclave, sgx_provision}`, for both in-tree and DCAP driver.  Some systems do have `/dev/sgx/{enclave, provision}` soft-linked to `/dev/{sgx_enclave, sgx_provision}` solely for backward compatibility. 

OE should switch to the newer `/dev/{sgx_enclave, sgx_provision}` nodes.

**Comment by radhikaj** [comment]
@haitaohuang - Can you please help with this? 
The enclave common loader takes care of this?
Can you please elaborate on what /dev/sgx/enclave get used?

**Comment by haitaohuang** [comment]
Yes enclave  common since 2.16 release would look for /dev/sgx_{enclave,provision} first and only falls back to /dev/sgx/{enclave,provision}. Our installer would continue to create symlinks for backward compatibility in case if some older SW still deployed. We are thinking about removing those symlinks in future. (https://github.com/intel/linux-sgx/issues/895), but unfortunately removing device nodes does break backward compatibility however small the chances are. So we will do it very slowly to avoid breaking existing usages. The  very _unlikely_ potential issues I can see:
1) user has their own runtime code developed for older kernel patches or DCAP driver looking for old nodes and not updated 
2) apps statically linked with an Intel urts or enclave_common library older than 2.16.
So if preferred for lower maintenance, I think OE newer releases can also switch to provide newer nodes of /dev/sgx_{...} for docker images and deprecate/remove older ones and/or provide some documentation for the changes similar to the approach Intel Kubernates device plugin adopted as described in above linked issue.

**Comment by CyanDevs** [comment]
Will do this with 2.19 which is out now.

**Comment by CyanDevs** [comment]
Thanks @the729 for noticing this issue. The related documentation and tests have been updated to use the newer device paths.
