### ISSUE TITLE
How to use OpenMP in Enclave?

### ISSUE THREAD

**Issue by ChampionNan** [openenclave/openenclave#4713]
How to use OpenMP in Enclave based on openenclave sdk? 
I already know the way about using OpenMP in intel sgx sdk.  Here is the link https://github.com/intel/linux-sgx/issues/826

**Comment by anakrish** [comment]
To use OpenMP in Enclave, the steps needed would be:
1. Build OpenMP from source against MUSL. You can do that by building OpenMP in Alpine Linux. Create a static library instead of shared library.

2. Link the enclave against the Open MP static library compiled against MUSL.
3. Implement any missing libc functions. Missing functions will appear as link errors.

**Comment by ChampionNan** [comment]
Got it, this looks like a lot of work. I'll give it a try, thanks!

**Comment by anakrish** [comment]
You could give [Mystikos](https://github.com/deislabs/mystikos) a try. It will make it easier to run applications within an SGX enclave.

**Comment by ChampionNan** [comment]
Sure. Thanks for your suggestion!

**Comment by anakrish** [comment]
I'm closing this for now. Feel free to reopen if needed.
