### ISSUE TITLE
Can I add any third-party library in enclave? 

### ISSUE THREAD

**Issue by ChampionNan** [openenclave/openenclave#4725]
I've known current support third-party libraries in enclave. Can I add third-party libraries according to my needs? How to do it?

I found the existing is: https://github.com/openenclave/openenclave/tree/master/3rdparty. It doesn't look like there's much existing supportings.

**Comment by anakrish** [comment]
@ChampionNan, 

Static libraries (.a archives) can be used within the enclave, dynamic libraries (.so shared libraries) cannot be used.
To use a static library within the enclave:
1. Compile the static library and any other library it uses against MUSL. To do this, you can:
   a. Build the library in Alpine Linux (it uses MUSL as its C library) and copy over the generated libraries.
   b. Or installl MUSL in your environment and use MUSL-gcc to compile your static library.
   c. Compile your static library using OE supplied libc headers (which are based on MUSL) instead of the default glibc headers available in your system.
2. Once you have built the static libraries, copy them over to the environment where you are building your enclave. Pass these libraries to the linker (via cmake or make).
3. There could be link errors due to missing libc functions since OE's MUSL based libc does not implement all the glibc functionality. You'd have to implement the missing functions yourself. If the missing function is not that important, you could provide a stub implementation that panics.
4. Once the enclave is able to be successfully linked, you'd have to detect as fix any runtime errors that may happen. These runtime errors could arise due to differences in libc on your system vs within the enclave.

Depending on the library you want to bring in, the above steps may be relatively easy to do, or they may turn out to be too complex. In the latter case, a library OS like [Mystikos](https://github.com/deislabs/mystikos) would be preferable.
