### ISSUE TITLE
Need standard networking APIs available within enclaves

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#866]
To ease porting of normal application code into an enclave, the POSIX socket APIs need to be supported.  By default, they should proxy to the host side.

**Comment by paulcallen** [comment]
seems like we would need the following ocall APIs:
- socket() creates a new socket of a certain socket type, identified by an integer number, and allocates system resources to it.
- bind() is typically used on the server side, and associates a socket with a socket address structure, i.e. a specified local port number and IP address.
- listen() is used on the server side, and causes a bound TCP socket to enter listening state.
- connect() is used on the client side, and assigns a free local port number to a socket. In case of a TCP socket, it causes an attempt to establish a new TCP connection.
- accept() is used on the server side. It accepts a received incoming attempt to create a new TCP connection from the remote client, and creates a new socket associated with the socket address pair of this connection.
- send() and recv(), or write() and read(), or sendto() and recvfrom(), are used for sending and receiving data to/from a remote socket.
- close() causes the system to release resources allocated to a socket. In case of TCP, the connection is terminated.
- gethostbyname() and gethostbyaddr() are used to resolve host names and addresses. IPv4 only.
- select() is used to suspend, waiting for one or more of a provided list of sockets to be ready to read, ready to write, or that have errors.
- poll() is used to check on the state of a socket in a set of sockets. The set can be tested to see if any socket can be written to, read from or if an error occurred.
- getsockopt() is used to retrieve the current value of a particular socket option for the specified socket.
- setsockopt() is used to set a particular socket option for the specified socket.

**Comment by dthaler** [comment]
Here's what I wrote elsewhere as the proposal:

The following POSIX socket APIs are exposed to trusted applications as well.  They simply map to calls to the normal (not secure world) networking stack, and so only signed and/or encrypted data should be used over these APIs.  

•	accept, bind, connect, FD_ISSET, freeaddrinfo, getaddrinfo, gethostname, getnameinfo, getpeername, getsockname, getsockopt, htonl, htons, inet_addr, listen, ntohl, ntohs, recv, select, send, setsockopt, shutdown, socket

The following Winsock APIs are also exposed to trusted applications as well, to ease porting of normal Windows applications:
•	closesocket, ioctlsocket, WSACleanup, WSAGetLastError, WSASetLastError, WSAStartup

**Comment by paulcallen** [comment]
is your expectation that the data sent over the socket is encrypted by these APIs or not? It really does not make sense to not automatically create a secure channel. Doing this would then completely change some of the APIs.

**Comment by paulcallen** [comment]
The following POSIX socket APIs are exposed to trusted applications as well.  They simply map to calls to the normal (not secure world) networking stack, and so only signed and/or encrypted data should be used over these APIs.  Since there may be a need to communicate with trusted peripherals as well, these should be #define’ed to oe_host_* equivalents by default, which have the same syntax as the POSIX equivalents, but have the actual implementation. 
•	accept, bind, connect, FD_ISSET, freeaddrinfo, getaddrinfo, gethostname, getnameinfo, getpeername, getsockname, getsockopt, htonl, htons, inet_addr, listen, ntohl, ntohs, recv, select, send, setsockopt, shutdown, socket
The following Winsock APIs are also exposed to trusted applications as well, to ease porting of normal Windows applications:
•	closesocket, ioctlsocket, WSACleanup, WSAGetLastError, WSASetLastError, WSAStartup

**Comment by radhikaj** [comment]
We have POSIX Socket APIs inside of enclaves. These work on Windows and Linux hosts. I am closing this as of now.
